environment: "#{Environment}#"
nodeEnvironment: "#{NodeEnvironment}#"
identityUrl: "#{IdentityUrl}#"
redisUrl: "#{RedisUrl}#"
mediaUrl: "#{MediaUrl}#"
catalogUrl: "#{CatalogUrl}#"
buyerUrl: "#{BuyerUrl}#"
logzIoToken: "#{LogzIoToken}#"
logzIoType: "#{LogzIoType}#"
logzIoDataCenterSubDomain: "#{LogzIoDataCenterSubDomain}#"
openTelemetryCollectorUrl: "#{OpenTelemetryCollectorUrl}#"
serverSideRenderingEndpoint: "#{ServerSideRenderingEndpoint}#"
applyRecipientEmail: "#{ApplyRecipientEmail}#"
senderEmail: "#{SenderEmail}#"
senderName: "#{SenderName}#"
sendGridApiKey: "#{SendGridApiKey}"
supportedCultures: "en,de,pl"
defaultCulture: "en"
identityApi:
  azureKeyVaultGiuruIdentityServer4Certificate: "#{IdentityApi--AzureKeyVaultGiuruIdentityServer4Certificate}#"
  azureKeyVaultClientId: "#{IdentityApi--AzureKeyVaultClientId}#"
  azureKeyVaultClientSecret: "#{IdentityApi--AzureKeyVaultClientSecret}#"
  connectionString: "#{IdentityApi--ConnectionString}#"
  actionSendGridCreateTemplateId: "#{IdentityApi--ActionSendGridCreateTemplateId}#"
  actionSendGridResetTemplateId: "#{IdentityApi--ActionSendGridResetTemplateId}#"
  actionSendGridTeamMemberInvitationTemplateId: "#{IdentityApi-ActionSendGridTeamMemberInvitationTemplateId}#"
  clients: "#{IdentityApi--Clients}#"
  sellerClientId: "#{IdentityApi--SellerClientId}#"
  accounts: "#{IdentityApi--Accounts}#"
  organisations: "#{IdentityApi--Organisations}#"
  privacyPolicy: "#{IdentityApi--PrivacyPolicy}#"
  regulations: "#{IdentityApi--Regulations}#"
  developersEmail: "#{IdentityApi--DevelopersEmail}#"
  replicas: "1"
  readinessProbe:
    initialDelaySeconds: "15"
    periodSeconds: "30"
    timeoutSeconds: "15"
  livenessProbe:
    initialDelaySeconds: "15"
    periodSeconds: "30"
    timeoutSeconds: "15"
accountWebReactSsr:
  replicas: "1"