apiVersion: v1
kind: Secret
metadata:
  name: b2b-identity-api-secrets
type: Opaque
data:
  RedisUrl: {{ .Values.redisUrl | b64enc | quote }}
  ConnectionString: {{ .Values.identityApi.connectionString | b64enc | quote }}
  LogzIoToken: {{ .Values.logzIoToken | b64enc | quote }}
  AzureKeyVaultGiuruIdentityServer4Certificate: {{ .Values.identityApi.azureKeyVaultGiuruIdentityServer4Certificate | b64enc | quote }}
  AzureKeyVaultClientId: {{ .Values.identityApi.azureKeyVaultClientId | b64enc | quote }}
  AzureKeyVaultClientSecret: {{ .Values.identityApi.azureKeyVaultClientSecret | b64enc | quote }}
  SendGridApiKey: {{ .Values.sendGridApiKey | b64enc | quote }}
  SellerClientId: {{ .Values.identityApi.sellerClientId | b64enc | quote }}
  Accounts: {{ .Values.identityApi.accounts | b64enc | quote }}
  Organisations: {{ .Values.identityApi.organisations | b64enc | quote }}
  Clients: {{ .Values.identityApi.clients | b64enc | quote }}