apiVersion: v1
kind: Service
metadata:
  name: identity-api-service
spec:
  type: ClusterIP
  selector:
    app: identity-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: account-web-react-ssr-service
spec:
  type: ClusterIP
  selector:
    app: account-web-react-ssr
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000