version: '3.9'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: unless-stopped
    depends_on:
      - jaeger
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    restart: unless-stopped

  redis:
    image: redis:alpine

  account-web-react-ssr:
    image: ${REGISTRY:-giuru}/account-web-react-ssr:${PLATFORM:-linux}-${TAG:-latest}
    build: 
      context: ../fe
      dockerfile: Dockerfile-ssr-local
    restart: unless-stopped

  identity-api:
    image: ${REGISTRY:-giuru}/identity-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Project/Services/Identity/Identity.Api/Dockerfile
    restart: unless-stopped
    depends_on:
      - sqldata
      - redis
      - account-web-react-ssr
