version: '3.9'

services:
  otel-collector:
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./DockerServices/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
      - "4318:4317"
      - "55679:55679"
    links:
      - jaeger
      - prometheus
      - loki

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=remote-write-receiver'
      - '--storage.tsdb.retention.time=1d'
      - '--storage.tsdb.retention.size=1GB'
    ports:
      - "9090:9090"

  loki:
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  jaeger:
    environment:
      - SPAN_STORAGE_TYPE=memory
    command: --memory.max-traces=100000
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"

  sqldata:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Gre@tPassw0rd
    ports:
      - "5433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  account-web-react-ssr:
    environment: 
      NODE_ENV: development
    volumes:
      - ../fe/server:/home/node/account-web-react-ssr/server
      - ../fe/src:/home/node/account-web-react-ssr/src

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RedisUrl=redis
      - ServerSideRenderingEndpoint=http://account-web-react-ssr:3000
      - MediaUrl=https://media.eltap.com
      - IdentityUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5105
      - LogstashUrl=http://logstash:31311
      - ConnectionString=Server=sqldata;Database=IdentityDb;User Id=sa;Password=Gre@tPassw0rd
      - Clients=663bba90-0036-4a58-8516-39faa8baba87&c61fcb32-cf9b-4cdd-84dc-4a1b173c36e9&${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5104;d9316849-7e98-4c5b-853b-5a322aecdc75&693667b0-545e-48b6-9ef8-02ada81be946&${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5107
      - SellerClientId=663bba90-0036-4a58-8516-39faa8baba87
      - Accounts=seller@user.com&Greg&Salesman&Gre@tPassw0rd&09affcc9-1665-45d6-919f-3d2026106ba1
      - Organisations=${ORGANISATION_ID}&ELTAP&eltap&eltap.com&True&EN&98daf0da-89ac-48db-8b9f-edc6383153ed&biuro@eltap.com&Fabryka%20mebli%20tapicerowanych%20ELTAP%20powsta%C5%82a%20w%201993%20roku.%20Jej%20za%C5%82o%C5%BCycielem%20jest%20Leszek%20Dworak%2C%20kt%C3%B3ry%20wraz%20w%20ma%C5%82%C5%BConk%C4%85%20prowadzi%C5%82%20firm%C4%99%20do%202020%20roku%20-%20od%20tego%20czasu%20firma%20zmieni%C5%82a%20status%20prawny%20na%20ELTAP%20Sp%C3%B3%C5%82ka%20z%20ograniczon%C4%85%20odpowiedzialno%C5%9Bci%C4%85%20Sp.k.%20do%20kt%C3%B3rej%20do%C5%82%C4%85czy%C5%82%20syn.%20Firma%20na%20przestrzeni%20lat%2C%20na%20skutek%20rozwoju%2C%20zyska%C5%82a%20miano%20znanej%20i%20cenionej%20marki%20na%20rynku%20polskim%20oraz%20mi%C4%99dzynarodowym.%20Przedsi%C4%99biorstwo%20posiada%2026-letnie%20do%C5%9Bwiadczenie%2C%20kt%C3%B3re%20poparte%20pasj%C4%85%20i%20zami%C5%82owaniem%20do%20meblarstwa%20sprawia%2C%20%C5%BCe%20produkowane%20meble%20zaspokajaj%C4%85%20gusta%20nawet%20najbardziej%20wymagaj%C4%85cych%20Klient%C3%B3w.%20Dzi%C5%9B%20firma%20ELTAP%20to%20przedsi%C4%99biorstwo%2C%20kt%C3%B3re%20specjalizuje%20si%C4%99%20w%20produkcji%20naro%C5%BCnik%C3%B3w%2C%20boxspring%C3%B3w%2C%20sof%2C%20foteli%2C%20%C5%82%C3%B3%C5%BCek%2C%20materacy%2C%20puf%20i%20wielu%20innych%20produkt%C3%B3w.%20Zatrudniamy%20ponad%20180%20pracownik%C3%B3w%2C%20a%20w%20zwi%C4%85zku%20z%20naszym%20rozwojem%20ci%C4%85gle%20poszukujemy%20nowych.%20Jeste%C5%9Bmy%20pr%C4%99%C5%BCnie%20rozwijaj%C4%85c%C4%85%20si%C4%99%20firm%C4%85%20z%20wykwalifikowan%C4%85%20za%C5%82og%C4%85%20specjalist%C3%B3w%2C%20kt%C3%B3ra%20dok%C5%82ada%20wszelkich%20stara%C5%84%2C%20aby%20nasze%20meble%20zapewnia%C5%82y%20komfortowy%20odpoczynek%20i%20zadawala%C5%82y%20gusta%20Klient%C3%B3w%20w%20ca%C5%82ej%20Europie.&The%20ELTAP%20upholstered%20furniture%20factory%20was%20established%20in%201993.%20Its%20founder%20was%20Leszek%20Dworak%2C%20who%20ran%20the%20company%20together%20with%20his%20wife%20until%202020%2C%20when%20the%20company%20changed%20its%20legal%20status%20to%20ELTAP%20Sp.%20z%20o.o.%20Sp.k.%20%28a%20limited%20liability%20partnership%29%20with%20the%20founder%E2%80%99s%20son%20joining%20as%20a%20partner.%20Over%20the%20years%20the%20company%20has%20grown%20into%20a%20well-known%20and%20valued%20brand%20in%20Polish%20and%20international%20markets.%20With%2026%20years%20of%20experience%20in%20the%20industry%2C%20backed%20by%20passion%20and%20a%20love%20for%20furniture%20making%2C%20the%20company%20is%20able%20to%20successfully%20supply%20even%20the%20most%20demanding%20of%20clients.%20Today%2C%20ELTAP%20specialises%20in%20the%20design%20and%20production%20of%20corner%20sofas%2C%20boxspring%20beds%2C%20couches%2C%20chairs%2C%20beds%2C%20mattresses%2C%20pouffes%2C%20and%20many%20other%20types%20of%20furniture.%20We%20have%20more%20than%20180%20employees%20and%20hiring%20more%20as%20we%20grow.%20We%20are%20a%20thriving%20company%20with%20a%20team%20of%20highly%20qualified%20specialists%20who%20make%20every%20effort%20to%20ensure%20that%20our%20furniture%20guarantees%20relaxation%2C%20lounging%20and%20sleeping%20in%20comfort%2C%20to%20the%20best%20satisfaction%20of%20customers%20across%20Europe.&Das%20Polsterm%C3%B6belwerk%20ELTAP%20wurde%201993%20gegr%C3%BCndet.%20Das%20Unternehmen%20wurde%20von%20Leszek%20Dworak%20gegr%C3%BCndet%2C%20der%20das%20Unternehmen%20zusammen%20mit%20seiner%20Frau%20bis%202020%20leitete.%20Zu%20dieser%20Zeit%20wurde%20der%20rechtliche%20Status%20des%20Unternehmens%2C%20dem%20der%20Sohn%20beigetreten%20ist%2C%20in%20ELTAP%20Sp%C3%B3%C5%82ka%20z%20ograniczon%C4%85%20odpowiedzialno%C5%9Bci%C4%85%20Sp.k.%20%5BGesellschaft%20mit%20beschr%C3%A4nkter%20Haftung%20Kommanditgesellschaft%5D%20ge%C3%A4ndert.%20Im%20Laufe%20der%20Jahre%20ist%20das%20Unternehmen%20aufgrund%20seiner%20Entwicklung%20sowohl%20auf%20dem%20polnischen%20Markt%20als%20auch%20international%20zu%20einer%20bekannten%20und%20angesehenen%20Marke%20geworden.%20Das%20Unternehmen%20verf%C3%BCgt%20%C3%BCber%2026%20Jahre%20Erfahrung%2C%20die%20in%20Verbindung%20mit%20Leidenschaft%20und%20Liebe%20zu%20M%C3%B6beln%20dazu%20f%C3%BChrt%2C%20dass%20die%20hergestellten%20M%C3%B6bel%20den%20Geschmack%20selbst%20der%20anspruchsvollsten%20Kunden%20befriedigen.%20Heute%20ist%20ELTAP%20ein%20Unternehmen%2C%20das%20sich%20auf%20die%20Herstellung%20von%20Ecksofas%2C%20Boxspringbetten%2C%20Sofas%2C%20Sesseln%2C%20Betten%2C%20Matratzen%2C%20Polsterhockern%20und%20vielen%20anderen%20Produkten%20spezialisiert.%20Wir%20besch%C3%A4ftigen%20%C3%BCber%20180%20Mitarbeiter%20und%20suchen%20aufgrund%20unserer%20Entwicklung%20st%C3%A4ndig%20nach%20neuen%20Arbeitskr%C3%A4ften.%20Wir%20sind%20ein%20dynamisch%20wachsendes%20Unternehmen%20mit%20einem%20qualifizierten%20Team%20von%20Fachleuten%2C%20das%20alle%20Anstrengungen%20unternimmt%2C%20um%20sicherzustellen%2C%20dass%20unsere%20M%C3%B6bel%20eine%20komfortable%20Erholung%20bieten%20und%20den%20Geschmack%20der%20Kunden%20in%20ganz%20Europa%20befriedigen.
      - SupportedCultures=${SUPPORTED_CULTURES}
      - PrivacyPolicy=Privacy%20Policy
      - Regulations=Regulations
      - BuyerUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5107
      - DefaultCulture=${DEFAULT_CULTURE}
      - ApplyRecipientEmail=office@eltap.com
      - SenderEmail=${SENDER_EMAIL}
      - SenderName=${SENDER_NAME}
      - SendGridApiKey=${SENDGRID_API_KEY}
      - ActionSendGridCreateTemplateId=${SENDGRID_CREATE_ACCOUNT_TEMPLATE_ID}
      - ActionSendGridResetTemplateId=${SENDGRID_RESET_PASSWORD_TEMPLATE_ID}
      - ActionSendGridTeamMemberInvitationTemplateId=${SENDGRID_TEAM_MEMBER_INVITATION_TEMPLATE_ID}
      - DevelopersEmail=it.developers@eltap.com
      - ContentGraphQlUrl=http://${GIURU_EXTERNAL_DNS_NAME_OR_IP}:5111/graphql
      - ContentGraphQlAuthorizationKey=${STRAPI_AUTHORIZATION_KEY}
      - OpenTelemetryTracingCollectorUrl=http://otel-collector:4317
      - OpenTelemetryMetricsCollectorUrl=http://otel-collector:4317
      - OpenTelemetryLogsCollectorUrl=http://otel-collector:4317
    ports:
      - "5105:80"

volumes:
  mssqldata:
    external: false
  redis:
    external: false